language: objective-c

osx_image: xcode7.3

install:
 - bundle install
 - bundle exec pod repo update --silent
 - bundle exec pod install

script:
 - xcodebuild -workspace 'mauth.xcworkspace' -scheme 'mauth' -sdk iphonesimulator CODE_SIGN_IDENTITY="" CODE_SIGNING_REQUIRED=NO test | xcpretty -c
