language: objective-c

branches:
 only:
 - statemachine

xcode_project: mauth.xcodeproj
xcode_scheme: mauthTests
osx_image: xcode7.2
xcode_sdk: iphonesimulator9.2

script:
- xcodebuild clean build test -project mauth.xcodeproj -scheme mauthTests
