language: objective-c

osx_image: xcode7.3

install:
 - pod install

before_install:
 - gem install cocoapods

script:
 - xcodebuild -workspace 'mauth.xcworkspace' -scheme 'mauth' -sdk iphonesimulator CODE_SIGN_IDENTITY="" CODE_SIGNING_REQUIRED=NO clean build | xcpretty -c
