language: objective-c

branches:
 only:
 - statemachine

xcode_project: mauth.xcworkspace
xcode_scheme: mauthTests
osx_image: xcode7.2
xcode_sdk: iphonesimulator9.2

script:
- xcodebuild clean build test -project mauth.xcworkspace -scheme mauthTests
