language: objective-c

osx_image: xcode7.2
xcode_sdk: iphonesimulator9.2

branches:
 only:
 - statemachine

script: xcodebuild -workspace mauth.xcworkspace -scheme mauth -sdk iphonesimulator9.2 ONLY_ACTIVE_ARCH=NO
