language: objective-c

branches:
 only:
 - master

osx_image: xcode7.2

xcode_sdk: iphonesimulator9.2
xcode_workspace: mauth.xcworkspace
xcode_scheme: mauth

install:
 - brew remove --force xctool
 - brew install xctool --HEAD
 - pod install

script:
 - xctool test -workspace mauth.xcworkspace -scheme mauth -sdk iphonesimulator9.2
